### ISSUE TITLE
exact search

### ISSUE THREAD

**Issue by fbstj** [PaleoCrafter/book-search#11]
there's a number of concepts or entities in the books which are either using dictionary words or are very short. the old search tool allows regular expression to be used in place of a case-insensitive "dumb" string match. this allows us to find pages mentioning "Pattern" or "Honor" or worse "Red" or "Vo" or "Ka" 

this may tie together with #4 or #6 to curate which chapters actually have those "special" terms in then

**Comment by fbstj** [comment]
also be aware of Yelig-nar for example aka potential hyphenated or apostrophied terms amongs maybe others, and preferably the various different curly quotes wouldn't effect results (in either search term or haystack)

**Comment by PaleoCrafter** [comment]
This is already addressed with the `text.cs` field for case sensitivity and the general behaviour of Elasticsearch (with my particular mapping strategy). Searches only show *whole* words by default, so searching `Vo` only brings up the character, not `Vorinism` or similar. If you want those kinds of substring searches, wildcards are the way to go.

As of eb4029cea396ba40f0193f4d7058af60c964107e, users also can get an overview of the peculiarities of the search thanks to a help dialog.
