### ISSUE TITLE
normalized book stylesheets

### ISSUE THREAD

**Issue by fbstj** [PaleoCrafter/book-search#5]
my older book-search tool had a fairly blunt tool for styling. it either kept the original epub styling which results in small text and weird fonts, or deleted the stylesheets entirely, causing some italics and emphasis to be lost

you may have solved the issue entirely already, but it would be cool to quickly review and potentially customise and normalise styles on the fly

**Comment by PaleoCrafter** [comment]
I've implemented a pretty straightforward manual mapping of CSS classes from the epub to a standardized set, which can be seen in the book upload or editing UI.

The list of supported styles can be found here:
https://github.com/PaleoCrafter/book-search/blob/eb4029cea396ba40f0193f4d7058af60c964107e/backend/src/main/kotlin/io/paleocrafter/booksearch/books/BookStyle.kt#L8-L24
I think they're sufficient for most books, but if you have any further ideas what could be added, I'm open to suggestions.
